In [1]:
import os
import subprocess
import pandas as pd
import numpy as np
import json
import glob
import requests

In [2]:
def setup_datasets():
    # 1. Clone AVeriTeC (Fact-checking Claims—used by Claimify)
    if not os.path.exists("averitec"):
        print("Cloning AVeriTeC...")
        subprocess.run(["git", "clone", "https://github.com/MichSchli/AVeriTeC.git", "averitec"])

    # 2. Clone SemEval-2020 Task 11 (Span-level Propaganda Labels)
    if not os.path.exists("semeval2020"):
        print("Downloading SemEval-2020 Task 11 dataset...")
        !wget -O "{"semeval-dataset.tgz"}" "{"https://zenodo.org/record/3952415/files/datasets-v2.tgz?download=1"}"
        print("Download complete.")

    # 3. Clone HQP (High-Quality Propaganda Social Media Dataset)
    if not os.path.exists("hqp"):
        print("Cloning HQP Dataset Repo...")
        subprocess.run(["git", "clone", "https://github.com/abdumaa/HiQualProp.git", "hqp"])

    print("\nDatasets initialized.")

if __name__ == "__main__":
    setup_datasets()

Cloning AVeriTeC...
Downloading SemEval-2020 Task 11 dataset...
--2026-02-14 01:08:18--  https://zenodo.org/record/3952415/files/datasets-v2.tgz?download=1
Resolving zenodo.org (zenodo.org)... 188.185.43.153, 188.184.103.118, 188.185.48.75, ...
Connecting to zenodo.org (zenodo.org)|188.185.43.153|:443... connected.
HTTP request sent, awaiting response... 301 MOVED PERMANENTLY
Location: /records/3952415/files/datasets-v2.tgz [following]
--2026-02-14 01:08:18--  https://zenodo.org/records/3952415/files/datasets-v2.tgz
Reusing existing connection to zenodo.org:443.
HTTP request sent, awaiting response... 200 OK
Length: 1142202 (1.1M) [application/octet-stream]
Saving to: ‘semeval-dataset.tgz’

semeval-dataset.tgz 100%[===================>]   1.09M  1.42MB/s    in 0.8s

2026-02-14 01:08:19 (1.42 MB/s) - ‘semeval-dataset.tgz’ saved [1142202/1142202]

Download complete.
Cloning HQP Dataset Repo...

Datasets initialized.

In [3]:
#Load AVeriTeC data into a dataframe
def load_averitec(file_path='averitec/data/dev.json'):
    with open(file_path, 'r') as f:
        data = json.load(f)

    # Flattening the JSON structure
    df = pd.json_normalize(data)
    return df

averitec = load_averitec()
averitec.head()

,claim,required_reannotation,label,justification,claim_date,speaker,original_claim_url,fact_checking_article,reporting_source,location_ISO_code,claim_types,fact_checking_strategies,questions,cached_original_claim_url
0,"In a letter to Steve Jobs, Sean Connery refuse...",False,Refuted,The answer and sources show that the claim was...,31-10-2020,None,None,https://web.archive.org/web/20201130144023/htt...,Facebook,None,[Event/Property Claim],[Written Evidence],[{'question': 'Where was the claim first publi...,None
1,Trump Administration claimed songwriter Billie...,False,Refuted,Seems that the Wzshington post accused the sin...,31-10-2020,None,None,https://web.archive.org/web/20201103001419/htt...,Instagram,US,"[Position Statement, Event/Property Claim]",[Written Evidence],[{'question': 'Has the Trump administration vo...,None
2,Due to Imran Khan's criticism of Macron's comm...,False,Refuted,The tweet was not the official government page...,31-10-2020,Consulate General Of Pakistan France,https://web.archive.org/web/20201113115127/htt...,https://web.archive.org/web/20210629013122/htt...,Twitter,FR,"[Causal Claim, Event/Property Claim]",[Written Evidence],[{'question': 'How did Macron criticise Islam?...,https://web.archive.org/web/20201113115127/htt...
3,UNESCO declared Nadar community as the most an...,False,Refuted,This claim is refuted. According to the QA pai...,31-10-2020,Kumar Shankar,None,https://web.archive.org/web/20210225110220/htt...,Facebook,IN,[Event/Property Claim],[Written Evidence],"[{'question': 'What is Nadar?', 'answers': [{'...",None
4,Republican Matt Gaetz was part of a company th...,True,Refuted,The company was sold in 2004 and the law suit ...,31-10-2020,,None,https://web.archive.org/web/20210713185816/htt...,Facebook,US,"[Numerical Claim, Event/Property Claim]","[Written Evidence, Numerical Comparison]",[{'question': 'Did Matt Gaetz work for Chemed ...,None

In [4]:
#Load HQP data into a dataframe
def load_hqp_labels(file_path='/content/hqp/Data/HiQualProp/HiQualProp.csv'):
    # This loads the IDs and the 'propaganda_strategy' labels
    df = pd.read_csv(file_path)
    return df

#id column shows Tweet ID but we have to run with Twitter API to get actual Tweet text
hqp = load_hqp_labels()
hqp.head()

                    id  labels           strategy  labels_weak1  labels_weak3
0  1372969669389393932       0  general discourse             0             0
1  1521594471279996928       0  general discourse             0             0
2  1385896329071632386       0  general discourse             0             1
3  1403386698835365888       0  general discourse             0             1
4  1509240723362795531       0  general discourse             0             1

In [11]:
tgz_path = "semeval-dataset.tgz"
print(os.path.exists(tgz_path), tgz_path)

# Make a target directory
extract_dir = "semeval2020_data"
os.makedirs(extract_dir, exist_ok=True)

# Extract with tar
!tar -xvzf "$tgz_path" -C "$extract_dir"

True semeval-dataset.tgz
datasets/
datasets/README.md
datasets/train-labels-task1-span-identification/
datasets/train-labels-task1-span-identification/article728972961.task1-SI.labels
datasets/train-labels-task1-span-identification/article111111136.task1-SI.labels
datasets/train-labels-task1-span-identification/article790667730.task1-SI.labels
datasets/train-labels-task1-span-identification/article770156851.task1-SI.labels
datasets/train-labels-task1-span-identification/article786250729.task1-SI.labels
datasets/train-labels-task1-span-identification/article766632016.task1-SI.labels
datasets/train-labels-task1-span-identification/article786344683.task1-SI.labels
datasets/train-labels-task1-span-identification/article999000880.task1-SI.labels
datasets/train-labels-task1-span-identification/article999000147.task1-SI.labels
datasets/train-labels-task1-span-identification/article696694316.task1-SI.labels
datasets/train-labels-task1-span-identification/article781847297.task1-SI.labels
datasets/train-labels-task1-span-identification/article762200179.task1-SI.labels
datasets/train-labels-task1-span-identification/article739091070.task1-SI.labels
datasets/train-labels-task1-span-identification/article999000184.task1-SI.labels
datasets/train-labels-task1-span-identification/article999001970.task1-SI.labels
datasets/train-labels-task1-span-identification/article699142854.task1-SI.labels
datasets/train-labels-task1-span-identification/article765385479.task1-SI.labels
datasets/train-labels-task1-span-identification/article711622457.task1-SI.labels
datasets/train-labels-task1-span-identification/article729670169.task1-SI.labels
datasets/train-labels-task1-span-identification/article770877978.task1-SI.labels
datasets/train-labels-task1-span-identification/article728758697.task1-SI.labels
datasets/train-labels-task1-span-identification/article111111115.task1-SI.labels
datasets/train-labels-task1-span-identification/article754111899.task1-SI.labels
datasets/train-labels-task1-span-identification/article999000124.task1-SI.labels
datasets/train-labels-task1-span-identification/article111111133.task1-SI.labels
datasets/train-labels-task1-span-identification/article730149656.task1-SI.labels
datasets/train-labels-task1-span-identification/article723883127.task1-SI.labels
datasets/train-labels-task1-span-identification/article734265267.task1-SI.labels
datasets/train-labels-task1-span-identification/article770156173.task1-SI.labels
datasets/train-labels-task1-span-identification/article729700539.task1-SI.labels
datasets/train-labels-task1-span-identification/article730865684.task1-SI.labels
datasets/train-labels-task1-span-identification/article758469195.task1-SI.labels
datasets/train-labels-task1-span-identification/article758812201.task1-SI.labels
datasets/train-labels-task1-span-identification/article769427494.task1-SI.labels
datasets/train-labels-task1-span-identification/article999001293.task1-SI.labels
datasets/train-labels-task1-span-identification/article700387229.task1-SI.labels
datasets/train-labels-task1-span-identification/article695833178.task1-SI.labels
datasets/train-labels-task1-span-identification/article694327499.task1-SI.labels
datasets/train-labels-task1-span-identification/article757843275.task1-SI.labels
datasets/train-labels-task1-span-identification/article741896049.task1-SI.labels
datasets/train-labels-task1-span-identification/article735815173.task1-SI.labels
datasets/train-labels-task1-span-identification/article787002327.task1-SI.labels
datasets/train-labels-task1-span-identification/article712382330.task1-SI.labels
datasets/train-labels-task1-span-identification/article701447437.task1-SI.labels
datasets/train-labels-task1-span-identification/article721890296.task1-SI.labels
datasets/train-labels-task1-span-identification/article713130996.task1-SI.labels
datasets/train-labels-task1-span-identification/article725238842.task1-SI.labels
datasets/train-labels-task1-span-identification/article999000155.task1-SI.labels
datasets/train-labels-task1-span-identification/article790777028.task1-SI.labels
datasets/train-labels-task1-span-identification/article716469423.task1-SI.labels
datasets/train-labels-task1-span-identification/article999001297.task1-SI.labels
datasets/train-labels-task1-span-identification/article730237078.task1-SI.labels
datasets/train-labels-task1-span-identification/article706661242.task1-SI.labels
datasets/train-labels-task1-span-identification/article757713354.task1-SI.labels
datasets/train-labels-task1-span-identification/article732154721.task1-SI.labels
datasets/train-labels-task1-span-identification/article731178960.task1-SI.labels
datasets/train-labels-task1-span-identification/article736231219.task1-SI.labels
datasets/train-labels-task1-span-identification/article704856340.task1-SI.labels
datasets/train-labels-task1-span-identification/article731063195.task1-SI.labels
datasets/train-labels-task1-span-identification/article729348908.task1-SI.labels
datasets/train-labels-task1-span-identification/article999000135.task1-SI.labels
datasets/train-labels-task1-span-identification/article795689901.task1-SI.labels
datasets/train-labels-task1-span-identification/article761546223.task1-SI.labels
datasets/train-labels-task1-span-identification/article729651527.task1-SI.labels
datasets/train-labels-task1-span-identification/article727736595.task1-SI.labels
datasets/train-labels-task1-span-identification/article999000133.task1-SI.labels
datasets/train-labels-task1-span-identification/article790483991.task1-SI.labels
datasets/train-labels-task1-span-identification/article706777811.task1-SI.labels
datasets/train-labels-task1-span-identification/article722512241.task1-SI.labels
datasets/train-labels-task1-span-identification/article732708002.task1-SI.labels
datasets/train-labels-task1-span-identification/article999000870.task1-SI.labels
datasets/train-labels-task1-span-identification/article788173482.task1-SI.labels
datasets/train-labels-task1-span-identification/article737255982.task1-SI.labels
datasets/train-labels-task1-span-identification/article778139122.task1-SI.labels
datasets/train-labels-task1-span-identification/article763440871.task1-SI.labels
datasets/train-labels-task1-span-identification/article707451080.task1-SI.labels
datasets/train-labels-task1-span-identification/article762340819.task1-SI.labels
datasets/train-labels-task1-span-identification/article731513824.task1-SI.labels
datasets/train-labels-task1-span-identification/article782086447.task1-SI.labels
datasets/train-labels-task1-span-identification/article738060046.task1-SI.labels
datasets/train-labels-task1-span-identification/article770376380.task1-SI.labels
datasets/train-labels-task1-span-identification/article707566605.task1-SI.labels
datasets/train-labels-task1-span-identification/article774904810.task1-SI.labels
datasets/train-labels-task1-span-identification/article730268758.task1-SI.labels
datasets/train-labels-task1-span-identification/article708487008.task1-SI.labels
datasets/train-labels-task1-span-identification/article725731328.task1-SI.labels
datasets/train-labels-task1-span-identification/article762546428.task1-SI.labels
datasets/train-labels-task1-span-identification/article697472447.task1-SI.labels
datasets/train-labels-task1-span-identification/article795693029.task1-SI.labels
datasets/train-labels-task1-span-identification/article706088110.task1-SI.labels
datasets/train-labels-task1-span-identification/article765913191.task1-SI.labels
datasets/train-labels-task1-span-identification/article735815503.task1-SI.labels
datasets/train-labels-task1-span-identification/article788726416.task1-SI.labels
datasets/train-labels-task1-span-identification/article789121798.task1-SI.labels
datasets/train-labels-task1-span-identification/article764715911.task1-SI.labels
datasets/train-labels-task1-span-identification/article758385628.task1-SI.labels
datasets/train-labels-task1-span-identification/article774637726.task1-SI.labels
datasets/train-labels-task1-span-identification/article697063039.task1-SI.labels
datasets/train-labels-task1-span-identification/article772947654.task1-SI.labels
datasets/train-labels-task1-span-identification/article765197039.task1-SI.labels
datasets/train-labels-task1-span-identification/article999000894.task1-SI.labels
datasets/train-labels-task1-span-identification/article715588833.task1-SI.labels
datasets/train-labels-task1-span-identification/article758386255.task1-SI.labels
datasets/train-labels-task1-span-identification/article697959084.task1-SI.labels
datasets/train-labels-task1-span-identification/article706501640.task1-SI.labels
datasets/train-labels-task1-span-identification/article786527921.task1-SI.labels
datasets/train-labels-task1-span-identification/article758756657.task1-SI.labels
datasets/train-labels-task1-span-identification/article721710340.task1-SI.labels
datasets/train-labels-task1-span-identification/article730389374.task1-SI.labels
datasets/train-labels-task1-span-identification/article770956434.task1-SI.labels
datasets/train-labels-task1-span-identification/article111111134.task1-SI.labels
datasets/train-labels-task1-span-identification/article738207834.task1-SI.labels
datasets/train-labels-task1-span-identification/article999001188.task1-SI.labels
datasets/train-labels-task1-span-identification/article721406153.task1-SI.labels
datasets/train-labels-task1-span-identification/article775448623.task1-SI.labels
datasets/train-labels-task1-span-identification/article735855251.task1-SI.labels
datasets/train-labels-task1-span-identification/article754131438.task1-SI.labels
datasets/train-labels-task1-span-identification/article771879020.task1-SI.labels
datasets/train-labels-task1-span-identification/article724791253.task1-SI.labels
datasets/train-labels-task1-span-identification/article696246189.task1-SI.labels
datasets/train-labels-task1-span-identification/article727634031.task1-SI.labels
datasets/train-labels-task1-span-identification/article789370909.task1-SI.labels
datasets/train-labels-task1-span-identification/article706636401.task1-SI.labels
datasets/train-labels-task1-span-identification/article790266787.task1-SI.labels
datasets/train-labels-task1-span-identification/article696264594.task1-SI.labels
datasets/train-labels-task1-span-identification/article790720480.task1-SI.labels
datasets/train-labels-task1-span-identification/article723823436.task1-SI.labels
datasets/train-labels-task1-span-identification/article790677230.task1-SI.labels
datasets/train-labels-task1-span-identification/article787668628.task1-SI.labels
datasets/train-labels-task1-span-identification/article731762731.task1-SI.labels
datasets/train-labels-task1-span-identification/article730573740.task1-SI.labels
datasets/train-labels-task1-span-identification/article727569885.task1-SI.labels
datasets/train-labels-task1-span-identification/article694811415.task1-SI.labels
datasets/train-labels-task1-span-identification/article718595845.task1-SI.labels
datasets/train-labels-task1-span-identification/article787955075.task1-SI.labels
datasets/train-labels-task1-span-identification/article761780613.task1-SI.labels
datasets/train-labels-task1-span-identification/article729549972.task1-SI.labels
datasets/train-labels-task1-span-identification/article730036755.task1-SI.labels
datasets/train-labels-task1-span-identification/article697454736.task1-SI.labels
datasets/train-labels-task1-span-identification/article755170235.task1-SI.labels
datasets/train-labels-task1-span-identification/article715790840.task1-SI.labels
datasets/train-labels-task1-span-identification/article711964584.task1-SI.labels
datasets/train-labels-task1-span-identification/article700461600.task1-SI.labels
datasets/train-labels-task1-span-identification/article700662577.task1-SI.labels
datasets/train-labels-task1-span-identification/article759337941.task1-SI.labels
datasets/train-labels-task1-span-identification/article723537899.task1-SI.labels
datasets/train-labels-task1-span-identification/article754508491.task1-SI.labels
datasets/train-labels-task1-span-identification/article999000145.task1-SI.labels
datasets/train-labels-task1-span-identification/article790665855.task1-SI.labels
datasets/train-labels-task1-span-identification/article727174208.task1-SI.labels
datasets/train-labels-task1-span-identification/article761969692.task1-SI.labels
datasets/train-labels-task1-span-identification/article111111111.task1-SI.labels
datasets/train-labels-task1-span-identification/article783702663.task1-SI.labels
datasets/train-labels-task1-span-identification/article723793978.task1-SI.labels
datasets/train-labels-task1-span-identification/article694356862.task1-SI.labels
datasets/train-labels-task1-span-identification/article763260610.task1-SI.labels
datasets/train-labels-task1-span-identification/article725824328.task1-SI.labels
datasets/train-labels-task1-span-identification/article795703371.task1-SI.labels
datasets/train-labels-task1-span-identification/article764664283.task1-SI.labels
datasets/train-labels-task1-span-identification/article764518567.task1-SI.labels
datasets/train-labels-task1-span-identification/article999000565.task1-SI.labels
datasets/train-labels-task1-span-identification/article763761219.task1-SI.labels
datasets/train-labels-task1-span-identification/article999000136.task1-SI.labels
datasets/train-labels-task1-span-identification/article706600938.task1-SI.labels
datasets/train-labels-task1-span-identification/article766942310.task1-SI.labels
datasets/train-labels-task1-span-identification/article728343601.task1-SI.labels
datasets/train-labels-task1-span-identification/article756114837.task1-SI.labels
datasets/train-labels-task1-span-identification/article730222442.task1-SI.labels
datasets/train-labels-task1-span-identification/article735265649.task1-SI.labels
datasets/train-labels-task1-span-identification/article770945799.task1-SI.labels
datasets/train-labels-task1-span-identification/article795379208.task1-SI.labels
datasets/train-labels-task1-span-identification/article777488669.task1-SI.labels
datasets/train-labels-task1-span-identification/article999000142.task1-SI.labels
datasets/train-labels-task1-span-identification/article698092698.task1-SI.labels
datasets/train-labels-task1-span-identification/article698503276.task1-SI.labels
datasets/train-labels-task1-span-identification/article727869189.task1-SI.labels
datasets/train-labels-task1-span-identification/article754179642.task1-SI.labels
datasets/train-labels-task1-span-identification/article779394730.task1-SI.labels
datasets/train-labels-task1-span-identification/article728680557.task1-SI.labels
datasets/train-labels-task1-span-identification/article111111112.task1-SI.labels
datasets/train-labels-task1-span-identification/article761334950.task1-SI.labels
datasets/train-labels-task1-span-identification/article782149225.task1-SI.labels
datasets/train-labels-task1-span-identification/article771655795.task1-SI.labels
datasets/train-labels-task1-span-identification/article698719689.task1-SI.labels
datasets/train-labels-task1-span-identification/article789370998.task1-SI.labels
datasets/train-labels-task1-span-identification/article769962236.task1-SI.labels
datasets/train-labels-task1-span-identification/article702077783.task1-SI.labels
datasets/train-labels-task1-span-identification/article709732928.task1-SI.labels
datasets/train-labels-task1-span-identification/article999000312.task1-SI.labels
datasets/train-labels-task1-span-identification/article759478604.task1-SI.labels
datasets/train-labels-task1-span-identification/article762147609.task1-SI.labels
datasets/train-labels-task1-span-identification/article111111114.task1-SI.labels
datasets/train-labels-task1-span-identification/article771546417.task1-SI.labels
datasets/train-labels-task1-span-identification/article795079843.task1-SI.labels
datasets/train-labels-task1-span-identification/article773748383.task1-SI.labels
datasets/train-labels-task1-span-identification/article111111123.task1-SI.labels
datasets/train-labels-task1-span-identification/article776616374.task1-SI.labels
datasets/train-labels-task1-span-identification/article788900262.task1-SI.labels
datasets/train-labels-task1-span-identification/article771254016.task1-SI.labels
datasets/train-labels-task1-span-identification/article787529309.task1-SI.labels
datasets/train-labels-task1-span-identification/article774007496.task1-SI.labels
datasets/train-labels-task1-span-identification/article999001287.task1-SI.labels
datasets/train-labels-task1-span-identification/article793534424.task1-SI.labels
datasets/train-labels-task1-span-identification/article741923579.task1-SI.labels
datasets/train-labels-task1-span-identification/article776368676.task1-SI.labels
datasets/train-labels-task1-span-identification/article780619695.task1-SI.labels
datasets/train-labels-task1-span-identification/article703056647.task1-SI.labels
datasets/train-labels-task1-span-identification/article111111122.task1-SI.labels
datasets/train-labels-task1-span-identification/article708071969.task1-SI.labels
datasets/train-labels-task1-span-identification/article696735702.task1-SI.labels
datasets/train-labels-task1-span-identification/article776345502.task1-SI.labels
datasets/train-labels-task1-span-identification/article111111131.task1-SI.labels
datasets/train-labels-task1-span-identification/article999001296.task1-SI.labels
datasets/train-labels-task1-span-identification/article757611486.task1-SI.labels
datasets/train-labels-task1-span-identification/article761897089.task1-SI.labels
datasets/train-labels-task1-span-identification/article786919720.task1-SI.labels
datasets/train-labels-task1-span-identification/article111111137.task1-SI.labels
datasets/train-labels-task1-span-identification/article708561738.task1-SI.labels
datasets/train-labels-task1-span-identification/article788056108.task1-SI.labels
datasets/train-labels-task1-span-identification/article698780559.task1-SI.labels
datasets/train-labels-task1-span-identification/article776049384.task1-SI.labels
datasets/train-labels-task1-span-identification/article703806098.task1-SI.labels
datasets/train-labels-task1-span-identification/article759468687.task1-SI.labels
datasets/train-labels-task1-span-identification/article729940206.task1-SI.labels
datasets/train-labels-task1-span-identification/article999001241.task1-SI.labels
datasets/train-labels-task1-span-identification/article727658675.task1-SI.labels
datasets/train-labels-task1-span-identification/article793467906.task1-SI.labels
datasets/train-labels-task1-span-identification/article757171650.task1-SI.labels
datasets/train-labels-task1-span-identification/article733754480.task1-SI.labels
datasets/train-labels-task1-span-identification/article699478811.task1-SI.labels
datasets/train-labels-task1-span-identification/article762152527.task1-SI.labels
datasets/train-labels-task1-span-identification/article728153988.task1-SI.labels
datasets/train-labels-task1-span-identification/article999001226.task1-SI.labels
datasets/train-labels-task1-span-identification/article776535164.task1-SI.labels
datasets/train-labels-task1-span-identification/article699291100.task1-SI.labels
datasets/train-labels-task1-span-identification/article729410793.task1-SI.labels
datasets/train-labels-task1-span-identification/article754348478.task1-SI.labels
datasets/train-labels-task1-span-identification/article722507879.task1-SI.labels
datasets/train-labels-task1-span-identification/article703698295.task1-SI.labels
datasets/train-labels-task1-span-identification/article999001032.task1-SI.labels
datasets/train-labels-task1-span-identification/article778664280.task1-SI.labels
datasets/train-labels-task1-span-identification/article764609985.task1-SI.labels
datasets/train-labels-task1-span-identification/article741802985.task1-SI.labels
datasets/train-labels-task1-span-identification/article769752554.task1-SI.labels
datasets/train-labels-task1-span-identification/article698018235.task1-SI.labels

In [6]:
base_dir = "semeval2020_data"

si_files = []
tc_files = []

for path in glob.glob(os.path.join(base_dir, "**", "*.labels"), recursive=True):
    fname = os.path.basename(path)
    if "task1-SI" in fname:
        si_files.append(path)
    elif "task2-TC" in fname:
        tc_files.append(path)

# Load SI (no technique column)
df_si_list = []
for path in si_files:
    df = pd.read_csv(
        path, sep="\t", header=None,
        names=["article_id", "start_char", "end_char"]
    )
    df["source_file"] = os.path.basename(path)
    df_si_list.append(df)
df_si = pd.concat(df_si_list, ignore_index=True)

# Load TC (with technique column second)
df_tc_list = []
for path in tc_files:
    df = pd.read_csv(
        path, sep="\t", header=None,
        names=["article_id", "technique", "start_char", "end_char"]
    )
    df["source_file"] = os.path.basename(path)
    df_tc_list.append(df)
df_tc = pd.concat(df_tc_list, ignore_index=True)
df_tc

,article_id,technique,start_char,end_char,source_file
0,111111111,Appeal_to_Authority,265,323,train-task2-TC.labels
1,111111111,Appeal_to_Authority,1795,1935,train-task2-TC.labels
2,111111111,Doubt,149,157,train-task2-TC.labels
3,111111111,Repetition,1069,1091,train-task2-TC.labels
4,111111111,Appeal_to_fear-prejudice,1334,1462,train-task2-TC.labels
...,...,...,...,...,...
12253,730573740,Black-and-White_Fallacy,4118,4224,article730573740.task2-TC.labels
12254,730573740,"Name_Calling,Labeling",1302,1322,article730573740.task2-TC.labels
12255,730573740,"Name_Calling,Labeling",1445,1467,article730573740.task2-TC.labels
12256,999000880,Flag-Waving,3114,3143,article999000880.task2-TC.labels
12257,999000880,Loaded_Language,2704,2709,article999000880.task2-TC.labels

In [7]:
text_files = glob.glob(os.path.join(base_dir, "**", "*.txt"), recursive=True)
print("Found text files:", text_files[:10])  # show a sample

articles = []

for path in text_files:
    fname = os.path.basename(path)          # e.g. "article763280007.txt"
    article_id_str = os.path.splitext(fname)[0]  # "article763280007"
    # Strip the "article" prefix if present
    if article_id_str.startswith("article"):
        article_id_str = article_id_str[len("article"):]  # "763280007"
    article_id = int(article_id_str)          # numeric to match labels

    with open(path, encoding="utf-8") as f:
        text = f.read()

    articles.append({"article_id": article_id, "text": text})

df_articles = pd.DataFrame(articles)
df_articles.head()

Found text files: ['semeval2020_data/datasets/dev-articles/article763280007.txt', 'semeval2020_data/datasets/dev-articles/article782448403.txt', 'semeval2020_data/datasets/dev-articles/article832910505.txt', 'semeval2020_data/datasets/dev-articles/article999000858.txt', 'semeval2020_data/datasets/dev-articles/article779309765.txt', 'semeval2020_data/datasets/dev-articles/article787085939.txt', 'semeval2020_data/datasets/dev-articles/article787730392.txt', 'semeval2020_data/datasets/dev-articles/article776385494.txt', 'semeval2020_data/datasets/dev-articles/article776126299.txt', 'semeval2020_data/datasets/dev-articles/article740235127.txt']

   article_id                                               text
0   763280007  Geert Wilders Puts the Political Elites On Not...
1   782448403  Federal judge rules against Trump administrati...
2   832910505  The Mueller Circus is Over, Long Live the Muel...
3   999000858  Stacey Abrams to Sue Georgia Over ‘Gross Misma...
4   779309765  Unbelievable!\nSharia New Mexico: Islamic comp...

In [8]:
sem_eval = df_tc.merge(df_articles[["article_id", "text"]], on="article_id", how="left")
sem_eval.head()

,article_id,technique,start_char,end_char,source_file,text
0,111111111,Appeal_to_Authority,265,323,train-task2-TC.labels,Next plague outbreak in Madagascar could be 's...
1,111111111,Appeal_to_Authority,1795,1935,train-task2-TC.labels,Next plague outbreak in Madagascar could be 's...
2,111111111,Doubt,149,157,train-task2-TC.labels,Next plague outbreak in Madagascar could be 's...
3,111111111,Repetition,1069,1091,train-task2-TC.labels,Next plague outbreak in Madagascar could be 's...
4,111111111,Appeal_to_fear-prejudice,1334,1462,train-task2-TC.labels,Next plague outbreak in Madagascar could be 's...

In [9]:
# Convert comma-separated technique strings to lists
sem_eval['technique'] = sem_eval['technique'].str.split(',')

# Clean up whitespace from each technique name
sem_eval['technique'] = sem_eval['technique'].apply(lambda x: [t.strip() for t in x])
sem_eval

,article_id,technique,start_char,end_char,source_file,text
0,111111111,[Appeal_to_Authority],265,323,train-task2-TC.labels,Next plague outbreak in Madagascar could be 's...
1,111111111,[Appeal_to_Authority],1795,1935,train-task2-TC.labels,Next plague outbreak in Madagascar could be 's...
2,111111111,[Doubt],149,157,train-task2-TC.labels,Next plague outbreak in Madagascar could be 's...
3,111111111,[Repetition],1069,1091,train-task2-TC.labels,Next plague outbreak in Madagascar could be 's...
4,111111111,[Appeal_to_fear-prejudice],1334,1462,train-task2-TC.labels,Next plague outbreak in Madagascar could be 's...
...,...,...,...,...,...,...
12253,730573740,[Black-and-White_Fallacy],4118,4224,article730573740.task2-TC.labels,Cardinal Müller: Blessing homosexual couples w...
12254,730573740,"[Name_Calling, Labeling]",1302,1322,article730573740.task2-TC.labels,Cardinal Müller: Blessing homosexual couples w...
12255,730573740,"[Name_Calling, Labeling]",1445,1467,article730573740.task2-TC.labels,Cardinal Müller: Blessing homosexual couples w...
12256,999000880,[Flag-Waving],3114,3143,article999000880.task2-TC.labels,They Are Coming: Migrant Caravan Resumes March...
12257,999000880,[Loaded_Language],2704,2709,article999000880.task2-TC.labels,They Are Coming: Migrant Caravan Resumes March...

In [10]:
#Only show relevant text being evaluated for each row (using span on text)
sem_eval['span_text'] = sem_eval.apply(lambda row: row['text'][row['start_char']:row['end_char']], axis=1)
sem_eval

,article_id,technique,start_char,end_char,source_file,text,span_text
0,111111111,[Appeal_to_Authority],265,323,train-task2-TC.labels,Next plague outbreak in Madagascar could be 's...,The next transmission could be more pronounced...
1,111111111,[Appeal_to_Authority],1795,1935,train-task2-TC.labels,Next plague outbreak in Madagascar could be 's...,when (the plague) comes again it starts from m...
2,111111111,[Doubt],149,157,train-task2-TC.labels,Next plague outbreak in Madagascar could be 's...,appeared
3,111111111,[Repetition],1069,1091,train-task2-TC.labels,Next plague outbreak in Madagascar could be 's...,"a very, very different"
4,111111111,[Appeal_to_fear-prejudice],1334,1462,train-task2-TC.labels,Next plague outbreak in Madagascar could be 's...,He also pointed to the presence of the pneumon...
...,...,...,...,...,...,...,...
12253,730573740,[Black-and-White_Fallacy],4118,4224,article730573740.task2-TC.labels,Cardinal Müller: Blessing homosexual couples w...,The Commandments are an expression of the Love...
12254,730573740,"[Name_Calling, Labeling]",1302,1322,article730573740.task2-TC.labels,Cardinal Müller: Blessing homosexual couples w...,theocentric humanism
12255,730573740,"[Name_Calling, Labeling]",1445,1467,article730573740.task2-TC.labels,Cardinal Müller: Blessing homosexual couples w...,suicidal modernization
12256,999000880,[Flag-Waving],3114,3143,article999000880.task2-TC.labels,They Are Coming: Migrant Caravan Resumes March...,We need people in our country
12257,999000880,[Loaded_Language],2704,2709,article999000880.task2-TC.labels,They Are Coming: Migrant Caravan Resumes March...,sheer